version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=ec2
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566" # LocalStack edge port
      - "4571:4571" # Lambda API endpoint
    volumes:
      - localstack-data:/var/tmp/localstack

volumes:
  postgres-data:
  localstack-data:
