name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'

    - name: Build the application
      run: go build -o gshub .

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY_PAIR }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa gshub ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }}:~

    - name: Connect to EC2 and restart service
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        sudo systemctl stop gshub.service || true
        sudo rm -rf /usr/local/bin/gshub
        sudo mv ~/gshub /usr/local/bin/gshub
        sudo systemctl start gshub.service
        EOF
