name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print secret names
      run: echo ${{ secrets.EC2_KEY_PAIR }}
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'

    - name: Build the application
      run: go build -o gshub .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gshub
        path: gshub

    - name: Remove existing directory
      run: rm -rf gshub

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: gshub
        path: gshub
      env:
        GOROOT: /opt/hostedtoolcache/go/1.22.3/x64

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY_PAIR }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa gshub ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_ID }}:~/gshub

    - name: Connect to EC2 and restart service
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_ID }} << 'EOF'
        sudo systemctl stop gshub.service || true
        mv ~/gshub /usr/local/bin/gshub
        sudo systemctl start gshub.service
        EOF
